variables:
  IMAGE_NAME: smrutipriya/demo-app
  IMAGE_TAG: myapp-1.0
stages:
  - test
  - build

build_image:
  stage: build
  image: docker:22.06.0-beta.0-cli
  services:
    - docker:22.06.0-beta.0-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_ID -p $DOCKER_PASSWD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG